# Generated by Django 4.0.4 on 2022-05-17 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('fullname', models.CharField(blank=True, max_length=200, null=True)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=500, null=True)),
                ('phone', models.IntegerField()),
                ('comment', models.TextField()),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
