# Generated by Django 4.0.4 on 2022-07-27 09:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0025_alter_teacher_tgender_alter_teacher_tqualification'),
        ('users', '0004_profile_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productName', models.CharField(blank=True, max_length=200, null=True)),
                ('teacherName', models.CharField(blank=True, max_length=200, null=True)),
                ('productPrice', models.PositiveIntegerField(blank=True, null=True)),
                ('duration', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('featured_image', models.ImageField(blank=True, default='products/default.jpg', null=True, upload_to='products/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('course', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminpanel.course')),
            ],
        ),
    ]
