# Generated by Django 4.0.4 on 2022-07-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='featured_image',
            field=models.ImageField(blank=True, default='../products/default.jpg', null=True, upload_to='../products/'),
        ),
    ]
