# Generated by Django 4.0.4 on 2022-07-27 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_product_course_alter_product_productname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
