# Generated by Django 4.0.4 on 2022-07-27 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0026_alter_student_stimage'),
        ('users', '0013_product_productname_alter_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='course',
        ),
        migrations.AlterField(
            model_name='product',
            name='productName',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminpanel.course'),
        ),
    ]
