# Generated by Django 4.0.4 on 2022-07-27 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0026_alter_student_stimage'),
        ('users', '0014_remove_product_course_alter_product_productname'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='course',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminpanel.course'),
        ),
        migrations.AlterField(
            model_name='product',
            name='productName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
