# Generated by Django 4.0.4 on 2022-07-28 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='semail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='sname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='sphone',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
