# Generated by Django 4.0.4 on 2022-07-28 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_order_semail_order_sname_order_sphone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='saddress',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='sgender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
