# Generated by Django 4.0.4 on 2022-09-09 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_order_saddress_order_sgender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='course',
        ),
    ]
