# Generated by Django 4.0.4 on 2022-09-09 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0027_alter_student_stimage'),
        ('users', '0020_remove_product_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='course',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='adminpanel.course'),
        ),
    ]
