# Generated by Django 4.0.4 on 2022-05-02 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='teacher_id',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='course_id',
        ),
    ]
