# Generated by Django 4.0.4 on 2022-05-02 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_remove_course_student_course_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='course',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='student',
        ),
    ]
