# Generated by Django 4.0.4 on 2022-05-02 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0006_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='TGender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=6),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='TQualification',
            field=models.CharField(choices=[('Under Graduate', 'Under Graduate'), ('Post Graduate', 'Post Graduate'), ('PhD', 'PhD')], max_length=16),
        ),
    ]
