# Generated by Django 4.0.4 on 2022-05-02 16:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0007_alter_teacher_tgender_alter_teacher_tqualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='TPhone',
            field=models.IntegerField(max_length=10),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('CNum', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('CName', models.CharField(max_length=100)),
                ('CPrice', models.IntegerField()),
                ('CDuration', models.IntegerField()),
                ('CTId', models.ManyToManyField(to='adminpanel.teacher')),
            ],
        ),
    ]
