# Generated by Django 4.0.4 on 2022-05-02 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0008_alter_teacher_tphone_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='CTId',
            new_name='CTName',
        ),
    ]
