# Generated by Django 4.0.4 on 2022-05-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0010_alter_teacher_tphone_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='StRemarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
