# Generated by Django 4.0.4 on 2022-05-02 16:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0011_alter_student_stremarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('FNum', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('FDate', models.DateTimeField(auto_now_add=True)),
                ('FAmount', models.IntegerField()),
                ('Admission', models.IntegerField()),
                ('Refundable_Deposit', models.IntegerField(default=3000)),
                ('FCourseName', models.ManyToManyField(to='adminpanel.course')),
                ('FStudName', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminpanel.student')),
            ],
        ),
    ]
