# Generated by Django 4.0.4 on 2022-05-04 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0013_alter_fee_admission_alter_student_stphone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='StGender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('others', 'others')], max_length=6),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='TGender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('others', 'others')], max_length=6),
        ),
    ]
