# Generated by Django 4.0.4 on 2022-05-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0015_alter_student_stphone_alter_teacher_tphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='StPhone',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='TPhone',
            field=models.IntegerField(max_length=10),
        ),
    ]
