# Generated by Django 4.0.4 on 2022-05-05 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0016_alter_student_stphone_alter_teacher_tphone'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fee',
            table='fee',
        ),
    ]
