# Generated by Django 4.0.4 on 2022-05-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0017_alter_fee_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='StCName',
        ),
        migrations.AddField(
            model_name='student',
            name='StCName',
            field=models.ManyToManyField(null=True, to='adminpanel.course'),
        ),
    ]
