# Generated by Django 4.0.4 on 2022-05-17 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0019_alter_student_stcname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='FStudName',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='adminpanel.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='StPhone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='TPhone',
            field=models.IntegerField(),
        ),
    ]
