# Generated by Django 4.0.4 on 2022-05-21 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0020_alter_fee_fstudname_alter_student_stphone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fee',
            options={'ordering': ['-FDate']},
        ),
        migrations.AddField(
            model_name='course',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
