# Generated by Django 4.0.4 on 2022-07-20 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0023_alter_course_cduration_alter_course_cprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='StGender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('others', 'others')], default='male', max_length=6),
        ),
    ]
