# Generated by Django 4.0.4 on 2022-07-27 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0024_alter_student_stgender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='TGender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('others', 'others')], default='male', max_length=6),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='TQualification',
            field=models.CharField(choices=[('Under Graduate', 'Under Graduate'), ('Post Graduate', 'Post Graduate'), ('PhD', 'PhD')], default='Under Graduate', max_length=16),
        ),
    ]
