# Generated by Django 4.0.4 on 2022-07-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0026_alter_student_stimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='StImage',
            field=models.ImageField(blank=True, default='profiles/avatar.jpg', null=True, upload_to='profiles/'),
        ),
    ]
